// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.kilo.domain;

import edu.unlv.kilo.domain.ItemAdjustment;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ItemAdjustment_Roo_Configurable {
    
    declare @type: ItemAdjustment: @Configurable;
    
}
