// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.kilo.domain;

import edu.unlv.kilo.domain.MoneyValue;

privileged aspect MoneyValue_Roo_JavaBean {
    
    public long MoneyValue.getAmount() {
        return this.amount;
    }
    
    public void MoneyValue.setAmount(long amount) {
        this.amount = amount;
    }
    
}
