// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.kilo.domain;

import edu.unlv.kilo.domain.MoneyValue;
import java.io.Serializable;

privileged aspect MoneyValue_Roo_Serializable {
    
    declare parents: MoneyValue implements Serializable;
    
}
