// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.kilo.domain;

import edu.unlv.kilo.domain.TransactionDescription;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TransactionDescription_Roo_Configurable {
    
    declare @type: TransactionDescription: @Configurable;
    
}
