// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.kilo.provider;

import edu.unlv.kilo.provider.Projection;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Projection_Roo_Configurable {
    
    declare @type: Projection: @Configurable;
    
}
