// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.kilo.domain;

import edu.unlv.kilo.domain.Projection;
import edu.unlv.kilo.domain.ProjectionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ProjectionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProjectionDataOnDemand: @Component;
    
    private Random ProjectionDataOnDemand.rnd = new SecureRandom();
    
    private List<Projection> ProjectionDataOnDemand.data;
    
    public Projection ProjectionDataOnDemand.getNewTransientProjection(int index) {
        Projection obj = new Projection();
        return obj;
    }
    
    public Projection ProjectionDataOnDemand.getSpecificProjection(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Projection obj = data.get(index);
        Long id = obj.getId();
        return Projection.findProjection(id);
    }
    
    public Projection ProjectionDataOnDemand.getRandomProjection() {
        init();
        Projection obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Projection.findProjection(id);
    }
    
    public boolean ProjectionDataOnDemand.modifyProjection(Projection obj) {
        return false;
    }
    
    public void ProjectionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Projection.findProjectionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Projection' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Projection>();
        for (int i = 0; i < 10; i++) {
            Projection obj = getNewTransientProjection(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
