// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.kilo.domain;

import edu.unlv.kilo.domain.Projection;
import edu.unlv.kilo.domain.ProjectionDataOnDemand;
import edu.unlv.kilo.domain.ProjectionIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProjectionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProjectionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProjectionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProjectionIntegrationTest: @Transactional;
    
    @Autowired
    private ProjectionDataOnDemand ProjectionIntegrationTest.dod;
    
    @Test
    public void ProjectionIntegrationTest.testCountProjections() {
        Assert.assertNotNull("Data on demand for 'Projection' failed to initialize correctly", dod.getRandomProjection());
        long count = Projection.countProjections();
        Assert.assertTrue("Counter for 'Projection' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProjectionIntegrationTest.testFindProjection() {
        Projection obj = dod.getRandomProjection();
        Assert.assertNotNull("Data on demand for 'Projection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Projection' failed to provide an identifier", id);
        obj = Projection.findProjection(id);
        Assert.assertNotNull("Find method for 'Projection' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Projection' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProjectionIntegrationTest.testFindAllProjections() {
        Assert.assertNotNull("Data on demand for 'Projection' failed to initialize correctly", dod.getRandomProjection());
        long count = Projection.countProjections();
        Assert.assertTrue("Too expensive to perform a find all test for 'Projection', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Projection> result = Projection.findAllProjections();
        Assert.assertNotNull("Find all method for 'Projection' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Projection' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProjectionIntegrationTest.testFindProjectionEntries() {
        Assert.assertNotNull("Data on demand for 'Projection' failed to initialize correctly", dod.getRandomProjection());
        long count = Projection.countProjections();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Projection> result = Projection.findProjectionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Projection' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Projection' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProjectionIntegrationTest.testFlush() {
        Projection obj = dod.getRandomProjection();
        Assert.assertNotNull("Data on demand for 'Projection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Projection' failed to provide an identifier", id);
        obj = Projection.findProjection(id);
        Assert.assertNotNull("Find method for 'Projection' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProjection(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Projection' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjectionIntegrationTest.testMergeUpdate() {
        Projection obj = dod.getRandomProjection();
        Assert.assertNotNull("Data on demand for 'Projection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Projection' failed to provide an identifier", id);
        obj = Projection.findProjection(id);
        boolean modified =  dod.modifyProjection(obj);
        Integer currentVersion = obj.getVersion();
        Projection merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Projection' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjectionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Projection' failed to initialize correctly", dod.getRandomProjection());
        Projection obj = dod.getNewTransientProjection(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Projection' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Projection' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Projection' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProjectionIntegrationTest.testRemove() {
        Projection obj = dod.getRandomProjection();
        Assert.assertNotNull("Data on demand for 'Projection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Projection' failed to provide an identifier", id);
        obj = Projection.findProjection(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Projection' with identifier '" + id + "'", Projection.findProjection(id));
    }
    
}
